version: '3.8'

services:
  # MongoDB service
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  # Backend API service
  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   container_name: tts-backend
  #   restart: always
  #   ports:
  #     - "5000:5000"
  #   environment:
  #     - MONGO_URI=mongodb://admin:password@mongodb:27017/
  #     - DB_NAME=synsere_tts
  #     - JWT_SECRET_KEY=your_secure_secret_key_change_in_production
  #   depends_on:
  #     - mongodb
  #   networks:
  #     - app-network

# Volume for MongoDB data persistence
volumes:
  mongodb_data:

# Network for services communication
networks:
  app-network:
    driver: bridge 